const incomeCategories:{emoji:string,name:string}[] = [
    { emoji: "💰", name: "Salary" },
    { emoji: "💼", name: "Freelancing" },
    { emoji: "📈", name: "Investments" },
    { emoji: "💡", name: "Side Hustle" },
    { emoji: "🏠", name: "Rental Income" },
    { emoji: "🎁", name: "Gifts & Grants" },
    { emoji: "💸", name: "Interest" },
    { emoji: "🛒", name: "Selling" },
    { emoji: "🔙", name: "Refunds" },
    { emoji: "🎉", name: "Bonuses" },
    { emoji: "💳", name: "Allowance" },
    { emoji: "👨‍👩‍👧‍👦", name: "Alimony/Child Support" },
    { emoji: "👑", name: "Royalties" },
    { emoji: "💼", name: "Commissions" },
    { emoji: "💡", name: "Tips" },
    { emoji: "🌐", name: "Online Income" },
    { emoji: "⏰", name: "Part-time Work" },
    { emoji: "📊", name: "Dividends" },
    { emoji: "🏅", name: "Grants" },
    { emoji: "🏰", name: "Inheritance" },
];
